blog/urls.py
from django.urls import path
from . import views
from .views import  PostListView,PostDetailView,PostCreateView,PostUpdateView,PostDeleteView



urlpatterns = [
    path('user/profile/<username>/', views.get_user_profile,name='user-profile'),
    path('' , PostListView.as_view() , name = 'blog-home'),
    path('posts/<int:pk>/' , PostDetailView.as_view() , name = 'post-detail'),
    path('posts/<int:pk>/delete/' , PostDeleteView.as_view() , name = 'post-delete'),
    path('posts/<int:pk>/update/' , PostUpdateView.as_view() , name = 'post-update'),
    path('posts/new/' , PostCreateView.as_view() , name = 'post-create'),
    path('about/', views.about , name = 'blog-about'),
    path('contact-us/', views.contact_us, name="blog-contact-us"),
    path('contact-us-success/', views.contact_us_success, name="blog-contact-us-success")

]

gis_dojo_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profile,name= 'profile'),
    path('', include('blog.urls')),
    path('', include('projects.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL ,document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views
from .views import  ProjectListView,ProjectDetailView


app_name = 'projects'
urlpatterns = [
    path('projects/', ProjectListView.as_view() , name = 'projects'),
    path('projects/<int:pk>/' , ProjectDetailView.as_view() , name = 'project-detail'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

# Create your models here.

# model for posts
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = RichTextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User , on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk':self.pk})

blog/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea,required=True)

blog/views.py
from django.shortcuts import render ,redirect
from .models import Post ,User
from django.views.generic import (ListView,DetailView,
                                  CreateView,UpdateView,DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.core.mail import send_mail,BadHeaderError
from .forms import ContactForm
from django.http import HttpResponse
from django.contrib import messages



# Create your views here.

#Creating home view
def home(request):
   posts = Post.objects.all()
   return render(request,'blog/index.html',{'posts':posts})


def get_user_profile(request,username):
    user = User.objects.get(username=username)
    return render(request,'blog/user_profile.html',{'user':user })

class PostListView(ListView):
   model = Post
   template_name = 'blog/index.html'
   context_object_name = 'posts'
   ordering = ['-date_posted']
   paginate_by = 5



class PostDetailView(DetailView):
   model = Post

class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title','content']

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Post
    fields = ['title','content']

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def about(request):
    context = {
        'posts': Post.objects.all().order_by('-date_posted')
    }

    return render(request, 'blog/about.html', context)

def contact_us (request):
    if request.method =='GET':
        form = ContactForm()
    else:
        form= ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject,message,from_email,['amdavy12@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found')
            messages.success(request, 'Your message has been sent!')
            return redirect('blog-home')
            #return render(request, 'blog/contact_us_success.html', {'title': 'contact_us_success'})


    return render(request , 'blog/contact_us.html', {'form':form})

def contact_us_success(request):
    return render(request,'blog/contact_us_success.html',{'title':'contact_us_success'})

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}

    <div class="content-section">
        <p><b>The GIS Dojo</b> is a blog that provides various information on Geographic
            Information Science.It is curated by David Munyiri with the help of various contributors. </p>
        <p>David holds a bachelors degree in Geospatial Information Science with IT from Maseno University.
            While undertaking his undergraduate studies in  the field of Geospatial Information  Sciences (GIS) at  the university ,
            he gained  in-depth  knowledge in  the use and application of GIS  in the development  of spatial  interventions for projects.</p>
        <p>Skilled in:
         <ul>
            <li>GIS data collection</li>
            <li>GIS data input</li>
            <li>GIS visualization</li>
            <li>spatial analysis</li>
            <li>network analysis </li>
            <li>Web mapping </li>
            <li>Programming (Python,Django,GeoDjango,HTML,CSS,Bootstrap,Leaflet) </li>
        </ul></P>
            <P>Mastery of ArcGIS Platforms (Desktop, Online and Server), GPS, QGIS, Google Earth and Microsoft Office User Specialist
            (MS Word, Excel, PowerPoint, Access) </p>

    </div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>The GIS Dojo</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
	<link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
	<!-- Social Share Kit CSS -->
	<link rel="stylesheet" href="{% static 'blog/social_share_kit/css/social-share-kit.css' %}" type="text/css">
	<!-- Font Awesome icons -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    

    
</head>
<body>
	<div id="fb-root"></div>
	<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v4.0"></script>

    <div class="container" style="box-shadow: 0 0 0 20px rgba(0,0,0,0.03); margin-bottom:30px;" >
		<div class="row" style="background-color:white;">
			<div class="mx-auto">
				<img src="{% static 'blog/logo4.png' %}">
			</div>
		</div>	
		<div class="row">
			<nav class="navbar navbar-expand-md navbar-dark bg-steel " style="width:100%">
				<div class="container">
				  <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Thinking Spatially</a>
				  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				  </button>
				  <div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto" >
					  <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
					  <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
						<a class="nav-item nav-link" href="{% url 'projects:projects' %}">Projects</a>
						<a class="nav-item nav-link" href="{% url 'blog-contact-us' %}">Contact Us</a>
					</div>
                <!-- Navbar Right Side -->
					<div class="navbar-nav">
						{% if user.is_staff %}
							 <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>
						{% endif %}
                        {% if user.is_authenticated %}

                             <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>

                        {% endif %}

					</div>
					</div>
				</div>
			</nav>
		</div>
		
			
				<div class="row " style="margin-top:15px;">

				
					<div class="col-lg-8 col-md-8 col-sm-6 col-xs-12 " style="margin-right:5px">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}">
                                        {{ message }}
                                    </div>
                                {% endfor%}
                            {% endif %}

							{% block content %} {% endblock %}

					</div>
					
					<div class="mx-auto col-lg-3 col-md-3 col-sm-5 col-xs-11 ">
						<div class="content-section">
							<h3>Social Sidebar</h3>
							<p class='text-muted'>Share this blog.</p>
							<div class="social">
								<div class="fb-share-button" data-href="{% url 'blog-home' %}" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
								<div class="twitter" >
									<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script
								</div>
							</div>
							  <ul class="list-group">

								{% for event in event_list %}
									<li class="list-group-item list-group-item-light">{{ event.name }}---{{ event.location }}---{{ event.date1|date:"F d, Y" }}</li>
								{% endfor %}
							  </ul>
						</div>
						
					</div>
				</div>
			
	</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="{% static 'blog/js/jquery-3.4.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<footer class="footer mt-auto py-3">
	  <div class="container">
		<span class="text-muted">© 2019 David Munyiri.</span>
	  </div>
	</footer>
</body>
</html>

blog/templates/blog/contact_us.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <h1><u>Send us a message..</u></h1>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy}}
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" href="{% url 'blog-contact-us-success'  %}" >Send</button>
            </div>

         </form>
    </div>
{% endblock content %}

blog/templates/blog/contact_us_success.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}


{% endblock content %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"/>
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-profile' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.content|safe|truncatewords:50 }}<a href="{% url 'post-detail' post.id %}">..more</a></p>
          </div>
        </article>
    {% endfor %}

    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page= {{ num }}"> {{ num }}</a>
            {% elif  num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page= {{ num }}"> {{ num }}</a>
            {% endif %}

        {% endfor%}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number}}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}


{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are your sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                 <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>

    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}

        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}"/>
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ object.author }}</a>
              <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
              {% if object.author == user %}
                <div>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id%}">Update</a>
                  <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id%}">Delete</a>
                </div>

              {% endif %}

            </div>
            <h2 class="article-title" >{{ object.title }}</h2>
            <p class="article-content">{{ object.content|safe }}</p>
             <div class="social" style="border-top: 1px solid #e3e3e3;">
                 <div>
                     <h5 class="text-muted">Share this post.</h5>
                 </div>
                 <div class="fb-share-button" data-href="{% url 'post-detail' post.id %}" data-layout="button_count" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
                <div class="twitter" >
                    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
             </div>
          </div>
        </article>
    <div id="disqus_thread" class="content-section"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = 'http://localhost:8000/post/{{ post.id }}';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '/{{ post.id }}/'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://gis-dojo-blog.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>



{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{%  load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                 {{ form.media }}
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>

    </div>
{% endblock content %}

blog/templates/blog/user_profile.html
{% extends "blog/base.html" %}
{%  load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>

    </div>
{% endblock content %}