blog/urls.py
from django.urls import path
from . import views
from .views import  PostListView,PostDetailView,PostCreateView,PostUpdateView,PostDeleteView



urlpatterns = [
    path('user/profile/<username>/', views.get_user_profile,name='user-profile'),
    path('' , PostListView.as_view() , name = 'blog-home'),
    path('posts/<int:pk>/' , PostDetailView.as_view() , name = 'post-detail'),
    path('posts/<int:pk>/delete/' , PostDeleteView.as_view() , name = 'post-delete'),
    path('posts/<int:pk>/update/' , PostUpdateView.as_view() , name = 'post-update'),
    path('posts/new/' , PostCreateView.as_view() , name = 'post-create'),
    path('about/', views.about , name = 'blog-about'),
    path('contact-us/', views.contact_us, name="blog-contact-us"),
    path('contact-us-success/', views.contact_us_success, name="blog-contact-us-success")

]

gis_dojo_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profile,name= 'profile'),
    path('', include('blog.urls')),
    path('', include('projects.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL ,document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views
from .views import  ProjectListView,ProjectDetailView


app_name = 'projects'
urlpatterns = [
    path('projects/', ProjectListView.as_view() , name = 'projects'),
    path('projects/<int:pk>/' , ProjectDetailView.as_view() , name = 'project-detail'),

]

projects/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Projects(models.Model):
    title = models.CharField(max_length=100)
    content = RichTextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User , on_delete=models.CASCADE)

    def __str__(self):
        return self.title

projects/views.py
from django.shortcuts import render
from django.views.generic import (ListView,DetailView,
                                  CreateView,UpdateView,DeleteView)
from .models import Projects

# Create your views here.
class ProjectListView(ListView):
    model = Projects
    template_name = 'projects/projects.html'
    context_object_name = 'projects'
    ordering = ['-date_posted']
    paginate_by = 5


class ProjectDetailView(DetailView):
    model = Projects

projects/templates/projects/projects.html
{% extends "blog/base.html" %}
{% block content %}
    {% for project in projects %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ project.author.profile.image.url }}"/>
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-profile' project.author.username %}">{{ project.author }}</a>
              <small class="text-muted">{{ project.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'projects:project-detail' project.id %}">{{ project.title }}</a></h2>
              <p class="article-content">{{ project.content|safe }}</p>
          </div>
        </article>
    {% endfor %}

    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page= {{ num }}"> {{ num }}</a>
            {% elif  num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page= {{ num }}"> {{ num }}</a>
            {% endif %}

        {% endfor%}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number}}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

{% endblock content %}

projects/templates/projects/projects_detail.html
{% extends "blog/base.html" %}
{% block content %}

        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}"/>
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ object.author }}</a>
              <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>


            </div>
            <h2 class="article-title" >{{ object.title }}</></h2>
            <p class="article-content">{{ object.content|safe }}</p>
              <div class="social" style="border-top: 1px solid #e3e3e3;">
                 <div>
                     <h5 class="text-muted">Share this project.</h5>
                 </div>
                 <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
                <div class="twitter" >
                    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
             </div>
          </div>
        </article>
    <div id="disqus_thread" class="content-section"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = 'http://localhost:8000/projects/{{ object.id }}';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '/{{ object.id }}/'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://gis-dojo-blog.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>


{% endblock content %}